export const DEFAULT_SETTINGS = {
  layoutMode: 'Grid',
  audioReactionMode: 'Ripple',
  audioGain: 2.5,
  audioHueShift: 60,
  baseHue: 11,
  objectSaturation: 100,
  audioBrightnessBoost: 55,
  backgroundColor: 225,
  backgroundBrightness: 22,
  textOverlay: "URBAN",
  customTextOverlayColor: false,
  textOverlayHue: 0,
  textOverlaySaturation: 100,
  textOverlayBrightness: 50,
  subTextOverlay: "SPEAK",
  mirrorShadow: true,
  mirrorAngle: 45,
  mirrorDistance: 4,
  mirrorHue: 0,
  mirrorSaturation: 100,
  mirrorBrightness: 50,
  mirrorOpacity: 100,
  mirrorFixedOpacity: false,
  customEffectColor: false,
  effectHue: 180,
  fontFamily: 'Orbitron',
  textHighlight: false,
  textHighlightMode: 'Default',
  textHighlightHue: 0,
  textHighlightSaturation: 100,
  textHighlightBrightness: 50,
  textHighlightOpacity: 100,
  textHighlightPadding: 12,
  textHighlightYOffset: 0,
  textHighlightBorder: false,
  textHighlightBorderHue: 0,
  textHighlightBorderSaturation: 100,
  textHighlightBorderBrightness: 50,
};

export const POPULAR_FONTS = [
  'Orbitron',
  'Roboto',
  'Open Sans',
  'Montserrat',
  'Lato',
  'Poppins',
  'Inter',
  'Nunito',
  'Playfair Display',
  'Rubik',
  'Oswald'
];
